# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'kebabPos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kebabPos
  pod 'SPIClient-iOS', '~> 2.0.5'


  target 'kebabPosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'kebabPosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
